name: BattlePlugin
version: ${project.version}
main: com.zect.battleplugin.BattlePlugin
depend: [ CommandAPI ]
api-version: 1.16
authors: [ Zect ]

commands:
  battle:
    description: battle helper command
    usage: |
      Use /help battle [subcommand] for more information
      /battle start - ゲーム開始
      /battle check - 現在の設定を表示
      /battle SetFightTeam [チーム名] - 参加チームに登録
      /battle SetWatchTeam [チーム名] - 観覧チームに登録
      /battle SetBorder - 範囲を指定
      /battle SetSpawn [チーム名] - 指定チームのスポーン地点を設定
      /battle SetTimeLimit [秒数] - 制限時間を設定
